// Mocks generated by Mockito 5.4.5 from annotations
// in ecommerce_app/test/features/products/presentation/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:ecommerce_app/features/products/domain/usecases/add_product.dart'
    as _i3;
import 'package:ecommerce_app/features/products/domain/usecases/delete_product.dart'
    as _i5;
import 'package:ecommerce_app/features/products/domain/usecases/get_products.dart'
    as _i2;
import 'package:ecommerce_app/features/products/domain/usecases/update_product.dart'
    as _i4;
import 'package:ecommerce_app/features/products/presentation/bloc/product_bloc.dart'
    as _i7;
import 'package:ecommerce_app/features/products/presentation/bloc/product_event.dart'
    as _i9;
import 'package:ecommerce_app/features/products/presentation/bloc/product_state.dart'
    as _i6;
import 'package:flutter/src/widgets/navigator.dart' as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetProducts_0 extends _i1.SmartFake implements _i2.GetProducts {
  _FakeGetProducts_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddProduct_1 extends _i1.SmartFake implements _i3.AddProduct {
  _FakeAddProduct_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProduct_2 extends _i1.SmartFake implements _i4.UpdateProduct {
  _FakeUpdateProduct_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteProduct_3 extends _i1.SmartFake implements _i5.DeleteProduct {
  _FakeDeleteProduct_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductState_4 extends _i1.SmartFake implements _i6.ProductState {
  _FakeProductState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBloc extends _i1.Mock implements _i7.ProductBloc {
  MockProductBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetProducts get getProducts =>
      (super.noSuchMethod(
            Invocation.getter(#getProducts),
            returnValue: _FakeGetProducts_0(
              this,
              Invocation.getter(#getProducts),
            ),
          )
          as _i2.GetProducts);

  @override
  _i3.AddProduct get addProduct =>
      (super.noSuchMethod(
            Invocation.getter(#addProduct),
            returnValue: _FakeAddProduct_1(
              this,
              Invocation.getter(#addProduct),
            ),
          )
          as _i3.AddProduct);

  @override
  _i4.UpdateProduct get updateProduct =>
      (super.noSuchMethod(
            Invocation.getter(#updateProduct),
            returnValue: _FakeUpdateProduct_2(
              this,
              Invocation.getter(#updateProduct),
            ),
          )
          as _i4.UpdateProduct);

  @override
  _i5.DeleteProduct get deleteProduct =>
      (super.noSuchMethod(
            Invocation.getter(#deleteProduct),
            returnValue: _FakeDeleteProduct_3(
              this,
              Invocation.getter(#deleteProduct),
            ),
          )
          as _i5.DeleteProduct);

  @override
  _i6.ProductState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProductState_4(this, Invocation.getter(#state)),
          )
          as _i6.ProductState);

  @override
  _i8.Stream<_i6.ProductState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.ProductState>.empty(),
          )
          as _i8.Stream<_i6.ProductState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i9.ProductEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.ProductEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.ProductState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.ProductEvent>(
    _i10.EventHandler<E, _i6.ProductState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i9.ProductEvent, _i6.ProductState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i10.Change<_i6.ProductState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i11.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i11.Route<dynamic>? route, _i11.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i11.Route<dynamic>? newRoute,
    _i11.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i11.Route<dynamic>? topRoute,
    _i11.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i11.Route<dynamic>? route,
    _i11.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
