name: ecom_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Network
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  dartz: ^0.10.1
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: CaveatBrush
      fonts:
        - asset: assets/fonts/CaveatBrush-Regular.ttf
